- name: patrik.uytterhoeven.PostgreSQL-For-RHEL6x
  scm: git
  src: https://github.com/Open-Future-Belgium/PostgreSQL.git
  version: master

- name: kostyrevaa.epel
  scm: git
  src: https://github.com/kostyrevaa/ansible-role-epel.git
  version: master

- name: koji-client
  scm: git
  src: https://github.com/kostyrevaa/ansible-koji-client.git
  version: master
