---
# tasks file for koji-db

- name: Main | Remove nodocs from yum.conf
  lineinfile: dest=/etc/yum.conf state=absent regexp="^tsflags="
  tags:
    - yum
    - koji-package

- name: Main | Install koji package with schema
  yum: name=koji state=present
  tags:
    - yum
    - koji-package

- name: Main | Import koji schema file'
  shell: "psql -U {{ koji_db_user }} {{ koji_dbname }} < $(rpm -qd koji | grep schema.sql) && touch /etc/koji.schema.done"
  args:
    creates: "/etc/koji.schema.done"
  tags:
    - koji-schema

